module.exports = {
    FB_PAGE_TOKEN: 'EAAegA9H9th0BAHSZCVsBqwAWTqZBklTIHNqaBZBEkNif5TZAqUHzhZBJbI6wHdqEtQZAsxzvlbYF3TRHD0ZBZAvTOEPBr8fuwwhkMRpfzQ7nMetfUZCqmb3Sl9v1HnpLoJEFmVTje1CX3tsDS7Ae0zmot2i5HLPZBttdS9sgk4H9YGsdm3oiTtjsRAGpWiDYQ81WgZD',
    FB_VERIFY_TOKEN: '',
    API_AI_CLIENT_ACCESS_TOKEN: '',
    FB_APP_SECRET: '',
    SERVER_URL: "",
}